[env:esp32-c3-devkitm-1]
; Pin stable SDK/toolchain set used in validated "no-reset" tests.
; Do not float to latest platform automatically.
platform = espressif32@2023.10.3
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  h2zero/NimBLE-Arduino@^1.4.2
  adafruit/Adafruit GFX Library@^1.11.9
  https://github.com/adafruit/Adafruit_GC9A01A.git
  ricmoo/QRCode@^0.0.1

build_flags =
  -DCORE_DEBUG_LEVEL=2
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
